### PR TITLE
Add tenant-scope arg for client certs

### PR DESCRIPTION
**Pull request by rimadeodhar**
This PR adds tenant scoping to the client certs
created for accessing tenant servers. Tenant
scopes were added as a way to restrict the ability
of client certs to validate with a specific set of
tenants in v22.2. Without tenant scoping, the client
certs created for tenant servers will not be able to
connect to non system tenant servers. This PR fixes
this problem by updating the client cert generation
command to specify the tenant scope argument while
creating client certs for tenant servers.

### CODE REVIEW

**Review by rimadeodhar — COMMENTED** [review]
Is there a way by which I can test this end to end with a specific CRDB binary?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/137#-:-N3RCjhRCbNXlpnX_HSP:bemqt23)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — CHANGES_REQUESTED** [review]
>  Is there a way by which I can test this end to end with a specific CRDB binary?

yes, you can write code like this:
```
testserver.NewTestServer(testserver.CockroachBinaryPathOpt("/path/to/your/binary"), testserver.SecureOpt())
```

> Also, once this is merged, what do I need to do to update the version? I presume I need to do a git tag along the lines of this https://go.dev/doc/modules/publishing? This is a non breaking change so just updating minor version should be sufficient.

yeah, just tag it as `v2.2.12` and then push it with `git push origin --tags`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/137#-:-N3WCZNq4KKFyQZW4y59:b9ywfvi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @rimadeodhar)

___
*[`testserver/tenant.go` line 80 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/137#-N3WCQ6Q66NK5TClwn1i:-N3WCQ6Q66NK5TClwn1j:bpv14fa) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/0baf39e6b3a4bea9b0f456ec970818d530f37848/testserver/tenant.go#L80)):*
> ```Go
> 		// Create tenant client certificate.
> 		certArgs := []string{"mt", "cert", "create-tenant-client", fmt.Sprint(tenantID)}
> 		var clientCertArgs []string
> ```

nit: is a name of `tenantScopedClientCertArgs` more clear?
___
*[`testserver/tenant.go` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/137#-N3WBx5i6Fq8J31Bl9ly:-N3WBx5i6Fq8J31Bl9lz:b-o7v4sg) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/0baf39e6b3a4bea9b0f456ec970818d530f37848/testserver/tenant.go#L81)):*
> ```Go
> 		certArgs := []string{"mt", "cert", "create-tenant-client", fmt.Sprint(tenantID)}
> 		var clientCertArgs []string
> 		if ts.version.AtLeast(version.MustParse("v22.2.0")) {
> ```

i believe you should add a separate if statement instead of modifying this one. otherwise the `certArgs` code will not  run for v22.1 as it should. also, should this version be `v22.2.0-alpha`?

**Review by rafiss — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
a test could be added to https://github.com/cockroachdb/cockroach-go/blob/master/testserver/testserver_test.go in `TestRunServer`. what  do you think?

**Review by rimadeodhar — COMMENTED** [review]
Hmm, I didn't feel the need since the SecureTenant test enforces the certificate generation already (which was how I tested this change using my custom cockroach binary). Do you feel like we need something in addition to that?  

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/137#-:-N3zR_jqE7E0d_c00cN6:b-na7kch)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Comment by rafiss** [comment]
ah, yup you're right! the `SecureTenant*NonStable` tests should cover this.

**Pull request merged**
