### PR TITLE
Add Makefile and circle.yaml file

### PR DESCRIPTION
**Pull request by spencerkimball**

### CODE REVIEW

**Comment by tamird** [comment]
Should be circle.yml, I think.

**Comment by mberhault** [comment]
LGTM. apparently it accepts both, but yes, `.yml` is what we've been using elsewhere.

**Comment by spencerkimball** [comment]
I fixed the `circle.yml` naming, but it's apparently not finding any tests in here. What gives?

**Comment by mberhault** [comment]
The first circleCI run showed no circle.yml config, but the second one did, it just failed on a "busy" cockroach binary. that may be solved by the issue you just assigned to me

**Comment by mberhault** [comment]
actually, it's not the issue you listed, it's because the tests are being run at the same time, so one of them is trying to run the binary while the other is still downloading it. blast, I need to find a way around that.

**Comment by spencerkimball** [comment]
Should I check this in?

**Comment by mberhault** [comment]
sure. I'll see what I can do to allow concurrent tests when downloading the binary. it's unrelated to this though.

**Pull request merged**
