### PR TITLE
crdb: detect wrapped HandledRetryableError

### LINKED ISSUE #16: should use `errors.Cause(err)` instead of `err` to check for retryable error
to allow this code to work correctly:

``` go
if err := tx.Exec("...."); err != nil {
    return errors.Wrap(err, "during insert")
}
```

### PR DESCRIPTION
**Pull request by benesch**
Teach ExecuteInTx to detect when a retryable error has been wrapped with
errors.Wrap.

Currently, returning a wrapped error from an ExecuteInTx closure will
break automatic transaction retries, as the error is no longer directly
marked as retryable. This is particularly hard to notice when code
is split across multiple functions. Consider the following:

    func doSomething(ctx context.Context, tx Tx) error {
        if err := doSomethingElse(ctx, tx); err != nil {
            return errors.Wrap("doSomethingElse", err)
        }
    }

    ... 8< ...

    ExecuteInTx(ctx, tx, func() error {
        return doSomething(ctx, tx)
    })

If the actions taken by doSomethingElse cause a retryable txn error
to be returned, doSomething will wrap the error. ExecuteTx thus won't see
the retryable error and the operation will fail.

Counterpart of cockroachdb/cockroach#21068 and its associated issue,
cockroachdb/cockroach#17667.

Fix #16.

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[crdb/cause.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-L1OL8o9E8YHjFLFtObE:-L1OL8oA6y5B9v8-I15H:b9vrbhy) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/01adbcf6485f9a1177a127961b9160028ffe4971/crdb/cause.go#L1)):*
> ```Go
> // Copyright (c) 2015, Dave Cheney <dave@cheney.net>
> ```

there's already errors.go, which mentions the `pkg/errors.Causer` interface. I think this code should be around there.

---

*[crdb/tx.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-L1OLNkRw-fPGu-rIVti:-L1OLNkRw-fPGu-rIVtj:bmzlrad) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/01adbcf6485f9a1177a127961b9160028ffe4971/crdb/tx.go#L62)):*
> ```Go
> // closure (fn). Any statements performed on the tx before ExecuteInTx is invoked will *not*
> // be re-run if the transaction needs to be retried.
> func ExecuteInTx(ctx context.Context, tx Tx, fn func() error) (err error) {
> ```

we should comment that `fn` can use pkg/errors to do wrapping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-:-L1OLSOeJvJgI99bQlHc:bnfp4nl)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[crdb/cause.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-L1OL8o9E8YHjFLFtObE:-L1Yo-ifOmpY4ZBYC9EI:b-afldm4) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/01adbcf6485f9a1177a127961b9160028ffe4971/crdb/cause.go#L1)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

there's already errors.go, which mentions the `pkg/errors.Causer` interface. I think this code should be around there.
</blockquote></details>

Well, it's got a separate license, so from that perspective it's better to have it in a separate file (although to be fully correct we need to note this in the top level as we did in the main repo). Or we could decide that the code here is trivial enough that we can include it without bringing in all the legalese. 

---

*[crdb/tx.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-L1OLNkRw-fPGu-rIVti:-L1YpVIEAg78AYWagxtr:bug51yv) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/01adbcf6485f9a1177a127961b9160028ffe4971/crdb/tx.go#L62)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

we should comment that `fn` can use pkg/errors to do wrapping
</blockquote></details>

Yeah, we should mention both `pkg/errors` and the fact if you wrap errors in other ways you can implement `Cause`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-:-L1Ypn_kQ0Hwv1uF3Ky5:bnfp4nl)*

**Comment by benesch** [comment]
Will do on the doc update. Ben, do you have a preference for which way to
go with the licensing?

**Comment by bdarnell** [comment]
I'd just copy it without the license. 

Also, make the Causer interface public so you can refer to it in docs (instead of an inline copy in both the code and docs).

**Comment by benesch** [comment]
Done. PTAL!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[crdb/tx.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-L1OLNkRw-fPGu-rIVti:-L1s-8mEUo-ukT9vj1OA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/01adbcf6485f9a1177a127961b9160028ffe4971/crdb/tx.go#L62)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Yeah, we should mention both `pkg/errors` and the fact if you wrap errors in other ways you can implement `Cause`. 
</blockquote></details>

Done.

---

*[crdb/cause.go, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-L1OL8o9E8YHjFLFtObE:-L1s-Birfm9SuL3uvNrt:bm3y2aw) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/01adbcf6485f9a1177a127961b9160028ffe4971/crdb/cause.go#L1)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Well, it's got a separate license, so from that perspective it's better to have it in a separate file (although to be fully correct we need to note this in the top level as we did in the main repo). Or we could decide that the code here is trivial enough that we can include it without bringing in all the legalese. 
</blockquote></details>

Ok, I just copied the code directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-:-L1s-GpiOGpZ9TODKpr-:b-qsvnon)*

**Comment by danhhz** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/46#-:-L59g5K9JdanZDiScb_h:b-jbsf8z)*

**Pull request merged**
