### PR TITLE
Don't swallow the original error when ROLLBACK TO SAVEPOINT fails

### LINKED ISSUE #36: original error clobbered in retry loop if ROLLBACK TO SAVEPOINT also fails
This line should combine the errors:

https://github.com/cockroachdb/cockroach-go/blob/41e9ceadabbc9fdff3017bc6b3d320ae74bd0129/crdb/tx.go#L106

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #36

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[crdb/tx.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvG359QUtmDWknHZCd:-KnvG359QUtmDWknHZCe:bunr5vk) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L113)):*
> ```Go
> 			// message and code. So, we'll do some surgery on lib/pq errors in
> 			// particular.
> 			// If it failed with any other error (e.g. the "driver: bad connection" is
> ```

nit: empty comment line above this line to preserve paragraph breaks

---

*[crdb/tx.go, line 120 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvGH3528x53O3sL7Lv:-KnvGH3528x53O3sL7Lw:b-i4u85o) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L120)):*
> ```Go
> 					rollbackPQErr.Message, pqErr.Code, pqErr.Message)
> 				return rollbackPQErr
> 			} else {
> ```

remove this `else` since you have an early return above.

---

*[crdb/tx.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvFvraADsULPFTL6BI:-KnvFvraADsULPFTL6BJ:bn9l5f8) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L121)):*
> ```Go
> 				return rollbackPQErr
> 			} else {
> 				return errors.New(fmt.Sprintf(msgPattern, err.Error(), pqErr.Code, pqErr.Message))
> ```

why not `fmt.Errorf`?

---

*[crdb/tx.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvGB1w-n6fIMmQAXvT:-KnvGB1w-n6fIMmQAXvU:b6iv5h5) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L121)):*
> ```Go
> 				return rollbackPQErr
> 			} else {
> 				return errors.New(fmt.Sprintf(msgPattern, err.Error(), pqErr.Code, pqErr.Message))
> ```

`.Error()` is superfluous

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[crdb/tx.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvG359QUtmDWknHZCd:-KnwJcrWdlAi4VPxityR:buev92c) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L113)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: empty comment line above this line to preserve paragraph breaks
</blockquote></details>

I've done this in the past, but I really don't like it and I want to stop doing it. There's a difference between a line break and a paragraph, more important in my opinion than the ability to wrap a whole comment at once.

---

*[crdb/tx.go, line 120 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvGH3528x53O3sL7Lv:-KnwLYuQ8xSL1hunzvLV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L120)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

remove this `else` since you have an early return above.
</blockquote></details>

Done.

---

*[crdb/tx.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvFvraADsULPFTL6BI:-KnwPPpEDFdlj9RdZw_K:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why not `fmt.Errorf`?
</blockquote></details>

Done.

---

*[crdb/tx.go, line 121 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvGB1w-n6fIMmQAXvT:-KnwPQ9_YYE-m80ZM1_5:b-ol1hkn) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L121)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

`.Error()` is superfluous
</blockquote></details>

indeed. And so was `.Message`, cause formatting is magic. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[crdb/tx.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvG359QUtmDWknHZCd:-KnwRgezT9JHslJg8c6H:b-wxwvto) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I've done this in the past, but I really don't like it and I want to stop doing it. There's a difference between a line break and a paragraph, more important in my opinion than the ability to wrap a whole comment at once.
</blockquote></details>

Seems like an odd principe to insist on. What's the difference between a line break and a paragraph?

---

*[crdb/tx.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnwRd6yP4gDkc1IJlFq:-KnwRd6z5AsC_KFueR6o:b-ito6ok) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/0cb86aa075d6fec599b695a93bc466e2bac10190/crdb/tx.go#L117)):*
> ```Go
> 			if rollbackPQErr, ok := err.(*pq.Error); ok {
> 				rollbackPQErr.Message = fmt.Sprintf(msgPattern,
> 					rollbackPQErr.Message, pqErr.Code, pqErr.Message)
> ```

are these `.Message`s also superfluous, then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Comment by andreimatei** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[crdb/tx.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvG359QUtmDWknHZCd:-KnwUkRI8NE7zaIuAErD:beb8em4) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L113)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Seems like an odd principe to insist on. What's the difference between a line break and a paragraph?
</blockquote></details>

I use paragraphs to separate different topics, and new lines within a block for... suggesting a stop in speech cadence, I suppose. Like here, a paragraph would be clearly wrong because the "if it failed" is in contrast to the "if" a few sentences above; the paragraph would break that relationship. The line break could be missing, but that would read worst to me because the previous branch of the if already has several sentences.

---

*[crdb/tx.go, line 117 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnwRd6yP4gDkc1IJlFq:-KnwUjyNP9UAHynpWkbb:b-hdmpfw) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/0cb86aa075d6fec599b695a93bc466e2bac10190/crdb/tx.go#L117)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

are these `.Message`s also superfluous, then?
</blockquote></details>

yeah, removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Comment by tamird** [comment]
:lgtm: but a test would be nice

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[crdb/tx.go, line 113 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnvG359QUtmDWknHZCd:-KnwXwTcQws_PZhKNkly:b-18jbot) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/904197427e92d70e3b29e9faadca2cab9c6ce922/crdb/tx.go#L113)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I use paragraphs to separate different topics, and new lines within a block for... suggesting a stop in speech cadence, I suppose. Like here, a paragraph would be clearly wrong because the "if it failed" is in contrast to the "if" a few sentences above; the paragraph would break that relationship. The line break could be missing, but that would read worst to me because the previous branch of the if already has several sentences.
</blockquote></details>

OK, I'll rescind my objection, but I think you've pointed out the oddity of this writing style.

I think you could write "Otherwise, we overwrite the error." and skip the line break altogether.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-:-KnwYLPHrVv2TiGNQQg2:buyi2ry)*

**Comment by andreimatei** [comment]
I've tested this by hand. A test doesn't seem easy to do to me because it's not easy to get the `rollback` to fail.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-:-KnwYm7xfIX3LCiJFeX_:b-8mwxsu)*

**Comment by tamird** [comment]
OK.

**Comment by andreimatei** [comment]
I've made a small change to the error string and it would appear that reviewable want you to click on the file revision.
I'm complaining about that in https://groups.google.com/a/cockroachlabs.com/forum/#!topic/eng/37pNjCgKrpw

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-:-KnzhvX0O997JU-VMKkM:b-tyvtkl)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[crdb/tx.go, line 114 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnzoklU0IJ0hfQDKHu8:-KnzoklVap2j63c8ZiKq:b-dofoy0) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/9c18163d0383035f91ca82ae4fffd511c1135aac/crdb/tx.go#L114)):*
> ```Go
> 			// If it failed with any other error (e.g. the "driver: bad connection" is
> 			// untyped), we overwrite the error.
> 			msgPattern := "Restarting txn failed. ROLLBACK TO SAVEPOINT encountered error: %s. " +
> ```

I believe errors aren't supposed to be title-cased

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[crdb/tx.go, line 114 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnzoklU0IJ0hfQDKHu8:-Knzsf9ryvog9wU0GEuY:b-5fl1w) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/9c18163d0383035f91ca82ae4fffd511c1135aac/crdb/tx.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I believe errors aren't supposed to be title-cased
</blockquote></details>

Well but when they have multiple sentences, what do you do?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Comment by tamird** [comment]
I think title-casing the second sentence is ok, but I wouldn't start with
title case because it doesn't compose well

On Jul 1, 2017 16:41, "Andrei Matei" <notifications@github.com> wrote:

Review status: all files reviewed at latest revision, 1 unresolved
discussion.
------------------------------

*crdb/tx.go, line 114 at r4
<https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnzoklU0IJ0hfQDKHu8:-Knzsf9ryvog9wU0GEuY:b-5fl1w>
(raw file
<https://github.com/cockroachdb/cockroach-go/blob/9c18163d0383035f91ca82ae4fffd511c1135aac/crdb/tx.go#L114>):*
*Previously, tamird (Tamir Duberstein) wrote…*

I believe errors aren't supposed to be title-cased

Well but when they have multiple sentences, what do you do?
------------------------------

*Comments from Reviewable
<https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37>*

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach-go/pull/37#issuecomment-312454510>,
or mute the thread

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-:-KoE-QCKqB_riFHD0njr:bnfp4nl)*

**Comment by andreimatei** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[crdb/tx.go, line 114 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnzoklU0IJ0hfQDKHu8:-KoE1hgyu4PWk_X6tBqA:bh6u7gj) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/9c18163d0383035f91ca82ae4fffd511c1135aac/crdb/tx.go#L114)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

*crdb/tx.go, line 114 at r4 <https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37#-KnzoklU0IJ0hfQDKHu8:-Knzsf9ryvog9wU0GEuY:b-5fl1w> (raw file <https://github.com/cockroachdb/cockroach-go/blob/9c18163d0383035f91ca82ae4fffd511c1135aac/crdb/tx.go#L114>):* *Previously, tamird (Tamir Duberstein) wrote…*

I believe errors aren't supposed to be title-cased

Well but when they have multiple sentences, what do you do? 
</blockquote></details>

lower-cased

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/37)*

**Pull request merged**
