### PR TITLE
testserver: use listening URL file to get SQL URL

### PR DESCRIPTION
**Pull request by benesch**
Use the new `--listening-url-file` flag to specify a file in which the SQL URL will be written. This flag was added in cockroachdb/cockroach#15468 for exactly this purpose, and makes this testserver resilient to changes in what log output is printed where. Closes #29.

/cc @knz this solves the problem rather neatly :). Really we should never have been parsing stdout.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/30)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

Forgot I just merged that :woman_facepalming: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[testserver/testserver.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-KjDd1zJ3yUHU1gB1GGk:-KjDd1zJ3yUHU1gB1GGl:b-ouy089) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/c983bb184e98b8f936ef25f15cd1ab330d5890ff/testserver/testserver.go#L76)):*
> ```Go
> 
> 	// Import postgres driver.
> ```

why the newline?

---

*[testserver/testserver.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-KjDdiuZgnk3EG4S9OmA:-KjDdGKEvd8WZXDDXRfU:b7m51rr) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/c983bb184e98b8f936ef25f15cd1ab330d5890ff/testserver/testserver.go#L252)):*
> ```Go
> 		ts.mu.Lock()
> 		if ts.state != stateRunning {
> 			return fmt.Errorf("server stopped or crashed before listening URL file was available")
> ```

this returns without unlocking, which doesn't seem great?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-:-KjDecBooa1FEbIEM_hp:bq4r448)*

**Comment by benesch** [comment]
Yeah, I thought it was pretty hilarious you sheparded that PR.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[testserver/testserver.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-KjDd1zJ3yUHU1gB1GGk:-KjEHCPWXpntdIbJrQNV:b8pelt7) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/c983bb184e98b8f936ef25f15cd1ab330d5890ff/testserver/testserver.go#L76)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

why the newline?
</blockquote></details>

Oops. Thanks.

---

*[testserver/testserver.go, line 252 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-KjDdiuZgnk3EG4S9OmA:-KjEHEumNBs0nJBggSno:b-t4pgxw) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/c983bb184e98b8f936ef25f15cd1ab330d5890ff/testserver/testserver.go#L252)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

this returns without unlocking, which doesn't seem great?
</blockquote></details>

Eek! Thanks, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-:-KjEHJOghp0BItYHMJy-:b-8w8upi)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[testserver/testserver.go, line 76 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30#-KjDd1zJ3yUHU1gB1GGk:-KjEvOcfTPgXAoTJzDxP:bf5dn6h) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/c983bb184e98b8f936ef25f15cd1ab330d5890ff/testserver/testserver.go#L76)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Oops. Thanks.
</blockquote></details>

I think you left it =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/30)*

**Comment by benesch** [comment]
Eep, so I did. See #33.

**Pull request merged**
