### PR TITLE
Make testserver multi-node more robust.

### PR DESCRIPTION
**Pull request by RichardJCai**
- Fix race condition in pollListeningURLFile.
- Add Opts for init node timeout and poll listening url.
  - InitTimeoutOpt, PollListenURLTimeoutOpt
- Parallelize restart test

### CODE REVIEW

**Review by pawalt — CHANGES_REQUESTED** [review]
Is there any way we can test the added arguments? Maybe make a testserver configuration we know will timeout on init and time it to make sure the option is propogated properly?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-:-NC_gt-I-zvcCs7Zq6MB:b935jd5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @RichardJCai, and @ZhouXing19)

___
*[`testserver/testserver.go` line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_hky-3G4ChrD5sMyM:-NC_hky-3G4ChrD5sMyN:b-o4jte8) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver.go#L814)):*
> ```Go
> 		ts.mu.RLock()
> 
> 		nodeDir := fmt.Sprintf("%s%d", ts.baseDir, i)
> ```

Why do we need to remove the individual directories if we're going to removeAll after anyway? Is there some case in which we'd fail to remove a single node's directory but not the others?
___
*[`testserver/testserver_test.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_faAZABN-Da9y2gfR:-NC_faAZABN-Da9y2gfS:b-pwgjjw) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver_test.go#L463)):*
> ```Go
> 			for j := 0; j < 3; j++ {
> 				for {
> 					port, err := getFreePort()
> ```

This is a very edge case, but this could race if another process is attempting to get a port from`:0` at the same time. If that process does a TCP listen on `:0` between when these ports are allocated and the testserver is started, it could get assigned one of the ports you've allocated here.

I think if you just feed the testserver `:0` as the port to listen on, it'll start up guaranteeing port uniqueness, and you won't have to do any of this allocation.

**Comment by RichardJCai** [comment]
> Is there any way we can test the added arguments? Maybe make a testserver configuration we know will timeout on init and time it to make sure the option is propogated properly?
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-:-NC_gt-I-zvcCs7Zq6MB:b935jd5)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @RichardJCai, and @ZhouXing19)
> 
> _[`testserver/testserver.go` line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_hky-3G4ChrD5sMyM:-NC_hky-3G4ChrD5sMyN:b-o4jte8) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver.go#L814)):_
> 
> > ```go
> > 		ts.mu.RLock()
> > 
> > 		nodeDir := fmt.Sprintf("%s%d", ts.baseDir, i)
> > ```
> 
> Why do we need to remove the individual directories if we're going to removeAll after anyway? Is there some case in which we'd fail to remove a single node's directory but not the others?
> 
> _[`testserver/testserver_test.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_faAZABN-Da9y2gfR:-NC_faAZABN-Da9y2gfS:b-pwgjjw) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver_test.go#L463)):_
> 
> > ```go
> > 			for j := 0; j < 3; j++ {
> > 				for {
> > 					port, err := getFreePort()
> > ```
> 
> This is a very edge case, but this could race if another process is attempting to get a port from`:0` at the same time. If that process does a TCP listen on `:0` between when these ports are allocated and the testserver is started, it could get assigned one of the ports you've allocated here.
> 
> I think if you just feed the testserver `:0` as the port to listen on, it'll start up guaranteeing port uniqueness, and you won't have to do any of this allocation.

**Comment by RichardJCai** [comment]
> Is there any way we can test the added arguments? Maybe make a testserver configuration we know will timeout on init and time it to make sure the option is propogated properly?
> 
> > Reviewed all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-:-NC_gt-I-zvcCs7Zq6MB:b935jd5)_ status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @RichardJCai, and @ZhouXing19)
> 
> _[`testserver/testserver.go` line 814 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_hky-3G4ChrD5sMyM:-NC_hky-3G4ChrD5sMyN:b-o4jte8) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver.go#L814)):_
> 
> > ```go
> > 		ts.mu.RLock()
> > 
> > 		nodeDir := fmt.Sprintf("%s%d", ts.baseDir, i)
> > ```
> 
> Why do we need to remove the individual directories if we're going to removeAll after anyway? Is there some case in which we'd fail to remove a single node's directory but not the others?
> 
> _[`testserver/testserver_test.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_faAZABN-Da9y2gfR:-NC_faAZABN-Da9y2gfS:b-pwgjjw) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver_test.go#L463)):_
> 
> > ```go
> > 			for j := 0; j < 3; j++ {
> > 				for {
> > 					port, err := getFreePort()
> > ```
> 
> This is a very edge case, but this could race if another process is attempting to get a port from`:0` at the same time. If that process does a TCP listen on `:0` between when these ports are allocated and the testserver is started, it could get assigned one of the ports you've allocated here.
> 
> I think if you just feed the testserver `:0` as the port to listen on, it'll start up guaranteeing port uniqueness, and you won't have to do any of this allocation.

**Review by pawalt — APPROVED** [review]
LGTM. Your call on testing the new arguments. Functionality looks pretty obvious, but never hurts to have some tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-:-NCaSZYhDApLDUFwrUBd:b1qpm3h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss, @RichardJCai, and @ZhouXing19)

___
*[`testserver/testserver_test.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/148#-NC_faAZABN-Da9y2gfR:-NCaSTbn5KSxShv3y_Xp:bu0q9e3) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/dd2bfb9d61ce37d189e8ab2bc17f7684e1b9ad38/testserver/testserver_test.go#L463)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

> This is a very edge case, but this could race if another process is attempting to get a port from:0 at the same time. If that process does a TCP listen on :0 between when these ports are allocated and the testserver is started, it could get assigned one of the ports you've allocated here.

Yeah I thought about using `:0` but we need to know what address to feed into the `--join` flag which includes the port. Pretty annoying problem here.
</blockquote></details>

Hmmm that is annoying. Thanks for the clarification.

**Comment by RichardJCai** [comment]
>LGTM. Your call on testing the new arguments. Functionality looks pretty obvious, but never hurts to have some tests.

I'm allergic to adding tests for timeouts. Jk I'll add a simple one.

**Comment by RichardJCai** [comment]
Actually I'm gonna merge this as is, adding a testhook for timeout is somewhat annoying and I'm gonna try to get the testserver into CRDB before I leave.

**Pull request merged**
