### PR TITLE
testserver: improve error handling discipline

### PR DESCRIPTION
**Pull request by tamird**
Updates #38.

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[testserver/binaries.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39#-KnwWqx9sccAvu0aiGhy:-KnwWqx9sccAvu0aiGhz:b-ej619n) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/8b04c51017d4223ec65207fa6bd60262534bd31d/testserver/binaries.go#L42)):*
> ```Go
> 	}
> 
> 	return output.Close()
> ```

there's also a defer above. Is that cool?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39)*

**Comment by tamird** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[testserver/binaries.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39#-KnwWqx9sccAvu0aiGhy:-KnwXdKlrwrFe-xYUPUD:bfafh2n) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/8b04c51017d4223ec65207fa6bd60262534bd31d/testserver/binaries.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

there's also a defer above. Is that cool?
</blockquote></details>

I think so - the deferred one will probably always error in the success case but I think that's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[testserver/binaries.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39#-KnwWqx9sccAvu0aiGhy:-KnwZkdi7ESPE5wVTpfk:b-6a3b9r) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/8b04c51017d4223ec65207fa6bd60262534bd31d/testserver/binaries.go#L42)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I think so - the deferred one will probably always error in the success case but I think that's fine.
</blockquote></details>

consider adding a comment saying that we do Close() explicitly here to return the error despite the deferred one above, to save people like me from wondering if the other line was noticed.
Or better yet, I'd use a named return and conditionally overwrite it in the defer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39#-:-Knw_C3DUq_AJZciMrlL:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[testserver/binaries.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39#-KnwWqx9sccAvu0aiGhy:-KnwbKhBscdlhJKrsiGV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/8b04c51017d4223ec65207fa6bd60262534bd31d/testserver/binaries.go#L42)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

consider adding a comment saying that we do Close() explicitly here to return the error despite the deferred one above, to save people like me from wondering if the other line was noticed.
Or better yet, I'd use a named return and conditionally overwrite it in the defer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach-go/39)*

**Pull request merged**
