### PR TITLE
Allow passing in environment variables to the start command

### PR DESCRIPTION
**Pull request by rafiss**

### CODE REVIEW

**Review by pawalt — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`testserver/testservernode.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/152#-NGc7nV81vrAPIveje0e:-NGc7nV81vrAPIveje0f:b-t1mx5y) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/e6fc35e77bbd4bb46608573f4a15a26303d62310/testserver/testservernode.go#L51)):*
> ```Go
> 		"COCKROACH_TRUST_CLIENT_PROVIDED_SQL_REMOTE_ADDR=true",
> 		"COCKROACH_FORCE_DEV_VERSION=true",
> 		"COCKROACH_UPGRADE_TO_DEV_VERSION=true",
> ```

I'm sure I'm missing context here, but why do we always add the environment variables? Won't this force an upgrade even if the user doesn't want an upgrade to a dev version?
___
*[`testserver/testservernode.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/152#-NGc7VY48taIROp5vR-g:-NGc7VY48taIROp5vR-h:b-ibcoc4) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/e6fc35e77bbd4bb46608573f4a15a26303d62310/testserver/testservernode.go#L62)):*
> ```Go
> 		wr, err := newFileLogWriter(fmt.Sprintf("%s.%d", ts.stdout, i))
> 		if err != nil {
> 			return fmt.Errorf("unable to open file %s: %w", ts.stdout, err)
> ```

Can you update this error message to reflect the new filename
___
*[`testserver/testservernode.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/152#-NGc7bbj1bxmYPuiX5kg:-NGc7bbj1bxmYPuiX5kh:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/e6fc35e77bbd4bb46608573f4a15a26303d62310/testserver/testservernode.go#L71)):*
> ```Go
> 		wr, err := newFileLogWriter(fmt.Sprintf("%s.%d", ts.stderr, i))
> 		if err != nil {
> 			return fmt.Errorf("unable to open file %s: %w", ts.stderr, err)
> ```

ditto

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/152)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[`testserver/testservernode.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/152#-NGc7nV81vrAPIveje0e:-NGhnhpQ32eq59YPQUQ8:blifhk9) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/e6fc35e77bbd4bb46608573f4a15a26303d62310/testserver/testservernode.go#L51)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

I'm sure I'm missing context here, but why do we always add the environment variables? Won't this force an upgrade even if the user doesn't want an upgrade to a dev version?
</blockquote></details>

no prob - these env vars are new and also not too intuitive. essentially, the behavior is:
- one allows you to upgrade from an official version to a dev version https://github.com/cockroachdb/cockroach/pull/87468
- one allows you to upgrade from a dev version to an official version https://github.com/cockroachdb/cockroach/pull/90002

so they're just about what's allowed -- it doesn't actually force any upgrades

it's probably better for me to make a more general way of passing in env vars though. i'll do that instead.
___
*[`testserver/testservernode.go` line 62 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/152#-NGc7VY48taIROp5vR-g:-NGhpkSg6kuDshNy3L4u:bke4j6u) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/e6fc35e77bbd4bb46608573f4a15a26303d62310/testserver/testservernode.go#L62)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

Can you update this error message to reflect the new filename
</blockquote></details>

i got rid of this change since it's unrelated to this PR and doesn't actually help with what i was trying to get it to do
___
*[`testserver/testservernode.go` line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach-go/152#-NGc7bbj1bxmYPuiX5kg:-NGhqHST9oKxh8fKhjLk:bb7od0r) ([raw file](https://github.com/cockroachdb/cockroach-go/blob/e6fc35e77bbd4bb46608573f4a15a26303d62310/testserver/testservernode.go#L71)):*
<details><summary><i>Previously, pawalt (Peyton Walters) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

same

**Review by pawalt — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-go/152)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by pawalt** [comment]
squirrel

**Comment by rafiss** [comment]
thanks!

**Pull request merged**
