### PR TITLE
[crdb/sqlx] add sqlx adapter for crdb tx

### PR DESCRIPTION
**Pull request by masroorhasan**
Resolves: https://github.com/cockroachdb/cockroach-go/issues/72

### CODE REVIEW

**Comment by masroorhasan** [comment]
Thanks @rafiss - what is the best way to get this change ported over to `version-modules` branch and cut a release (say `v2.1.0` or something)?

**Comment by rafiss** [comment]
@masroorhasan Good question! This will be the first change that we port over to that branch, so I will work on doing it myself now and figure out a process.

**Comment by andreimatei** [comment]
Since CRDb now uses go modules, I think this repo can/should switch to modules (on master).

**Comment by rafiss** [comment]
I can give that a shot

**Comment by SWDevAngel** [comment]
@masroorhasan Hi Masroor. Thank you for contributing to CockroachDB this year. As a token of our appreciation we would like to send you a gift. Please DM me on our [community Slack](https://cockroa.ch/slack) `@lisa` so I can send you a link. (If you don’t want a gift, we also have a charitable contribution choice.) All orders need to be in by December 13, so please send this asap. :)

**Pull request merged**
